.TH MACUTIL L "October 22, 1992"
.UC
.SH NAME
macutil \- A package that deals with MacIntosh files on a Unix system
.SH DESCRIPTION
.I macutil
is a package that contains a number of utilities that deal with MacIntosh
files on a Unix system.
It contains the following programs:
.TP
.B binhex
Convert files to BinHex 4.0 compatible hexified form.
.TP
.B frommac
Receives files from the MacIntosh on the Unix system.
.TP
.B hexbin
Convert hexified files to their MacIntosh format.
.TP
.B macsave
Save a series of files from a MacBinary stream as individual files.
.TP
.B macstream
Combine a series of files to a MacBinary stream.
.TP
.B macunpack
Unpack a MacIntosh archive into its constituents.
.TP
.B tomac
Transmits files from the Unix system to a MacIntosh.
.SH BUGS
This manual page is hopelessly incomplete!
.SH SEE ALSO
binhex(1),
frommac(1),
hexbin(1),
macsave(1),
macstream(1),
macunpack(1),
tomac(1)
.SH AUTHOR
Dik T. Winter, CWI, Amsterdam, The Netherlands (dik@cwi.nl)
